apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-ss
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: mariadb-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      # initContainers:
      # - name: fix-permissions
      #   image: busybox
      #   command: ["sh", "-c", "chown -R 999:999 /var/lib/mysql"]
      #   securityContext:
      #     runAsUser: 0
      #     privileged: true
      #   volumeMounts:
      #   - name: maria-data
      #     mountPath: /var/lib/mysql
          
      securityContext:  
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: mariadb
        image: mariadb:10.11
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
        command: ["mysqld"]
        args:
          - "--innodb-buffer-pool-size=512M"
          - "--innodb-flush-log-at-trx-commit=2"
          - "--skip-name-resolve"
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: root-password
                name: mysql-pass
          - name: MARIADB_DATABASE
            value: wordpress
          - name: MARIADB_USER
            value: usr_pk
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db-password
                name: mysql-pass
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: maria-data
          mountPath: /var/lib/mysql
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - europe-west4-a
                      - europe-west4-b
                      - europe-west4-c
                      - europe-west1-b
                      - europe-west1-c
                      - europe-west1-d
  volumeClaimTemplates:
  - metadata:
      name: maria-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard-rwo
      resources:
        requests:
          storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
  clusterIP: None
